export const TODO_FETCH_LIST = 'TODO_FETCH_LIST'
export const TODO_FETCH_LIST_RESULT = 'TODO_FETCH_LIST_RESULT'

export const TODO_ADD = 'TODO_ADD'
export const TODO_ADD_RESULT = 'TODO_ADD_RESULT'

export const TODO_REMOVE = 'TODO_REMOVE'
export const TODO_REMOVE_RESULT = 'TODO_REMOVE_RESULT'